name: apply-infra
on:
  workflow_dispatch:
    inputs:
      path:
        description: "Path to the Terrafrom configuration"
        required: true
        default: "infrastructure/terraform/dev"

jobs:
  terraform-plan:
    name: ${{ inputs.path }} terraform-plan 
    uses: aplaceformom/terraform-plan/.github/workflows/terraform-plan.yaml@v1
    with:
      path: "${{ inputs.path }}"
      awsRole: "arn:aws:iam::373477481654:role/${YOUR_SERVICE_NAME}-${DEPLOYMENT_SLOT}-deploy"
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: read
  approval:
    name: approval ${{ inputs.path }}
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment: infrastructure
    steps:
      - name: manual-approval
        run: echo "Hit approve in the GitHub UI"
  terraform-apply:
    name: terraform-apply ${{ inputs.path }}
    needs: approval
    uses: aplaceformom/terraform-apply/.github/workflows/terraform-apply.yaml@v1
    with:
      path: "${{ inputs.path }}"
      awsRole: "arn:aws:iam::373477481654:role/${YOUR_SERVICE_NAME}-${DEPLOYMENT_SLOT}-deploy"
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: read
