name: apply-alerts
on:
  workflow_dispatch:
    inputs:
      path:
        description: "Path to the Terraform alerts configuration"
        required: true
        default: "infrastructure/alerts/prod"

jobs:
  terraform-plan:
    uses: aplaceformom/terraform-plan/.github/workflows/terraform-plan.yaml@v1.0.4
    with:
      path: "${{ inputs.path }}"
      awsRole: "arn:aws:iam::373477481654:role/${{github.event.repository.name}}-deploy"
      terraformVersion: "1.9.8"
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: read
  approval:
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment: infrastructure
    steps:
      - name: manual-approval
        run: echo "Hit approve in the GitHub UI"
  terraform-apply:
    needs: approval
    uses: aplaceformom/terraform-apply/.github/workflows/terraform-apply.yaml@v1.0.4
    with:
      path: "${{ inputs.path }}"
      awsRole: "arn:aws:iam::373477481654:role/${{github.event.repository.name}}-deploy"
      terraformVersion: "1.9.8"
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: read
