name: Infrastructure Plan
on:
  workflow_dispatch:
    inputs:
      path:
        description: "Path to the Terrafrom configuration"
        required: true
        type: choice
        options:
          - "infrastructure/terraform/dev"
          - "infrastructure/terraform/qa"
          - "infrastructure/terraform/prod"

jobs:
  terraform-plan:
    name: ${{ inputs.path }} terraform-plan
    uses: aplaceformom/terraform-plan/.github/workflows/terraform-plan.yaml@v1.0.4
    with:
      path: "${{ inputs.path }}"
      awsRole: "arn:aws:iam::373477481654:role/${{github.event.repository.name}}-deploy"
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: read
