# This file is used to run the CI checks on the main branch
# It can be deleted when deployments are setup

name: main-analysis

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 22

    steps:
      - uses: actions/checkout@v4

      - name: Build NestJS Application
        uses: ./.github/actions/build
        with:
          nodeVersion: ${{ env.NODE_VERSION }}
          nodeAuthToken: ${{ secrets.NODE_AUTH_TOKEN }}
          cache: "pnpm"

      - name: CI Checks
        uses: ./.github/actions/ci-checks
        with:
          nodeVersion: ${{ env.NODE_VERSION }}
          nodeAuthToken: ${{ secrets.NODE_AUTH_TOKEN }}
          sonarToken: ${{ secrets.SONAR_TOKEN }}
          sonarHostUrl: ${{ secrets.SONAR_HOST_URL }}
          cache: "pnpm"
